spring.application.name=lecture-10-springboot-application-properties

payment-property.type=Paytm
#payment-property.retry-count=5
payment-property.retry-count=5
payment-property.isEnabled=true
payment-property.timeout=3000
